[project]
name = "soundlab"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "guibbon>=0.3.0",
    "librosa>=0.11.0",
    "matplotlib>=3.10.1",
    "pygame>=2.6.1",
    "scipy>=1.15.2",
]
